window.MTULIVU_QUOTES = [
  "Peace is not later. It is the next unhurried breath.",
  "Sit as if the earth already knows your name.",
  "The mind will sprint. Let the body walk.",
  "A quiet chest can hold a loud day.",
  "Nothing you dropped in silence was truly lost.",
  "Breathe once more than you think you need.",
  "Stillness is not empty. It is crowded with enough.",
  "If the mind is loud, sit closer to the body.",
  "You do not have to finish becoming to begin resting.",
  "Let the morning arrive without a speech.",
  "The pause between thoughts is also a home.",
  "Kindness toward yourself is not a side practice.",
  "Hurry is a rumor. Breath is the news.",
  "Close the eyes. Open the hour.",
  "What you stop chasing often sits down beside you.",
  "The body keeps a slower clock. Trust it.",
  "Peace does not perform. It waits.",
  "A single honest breath outranks a clever plan.",
  "Let the jaw unlearn the day.",
  "You are allowed to be unfinished and still sit.",
  "The sky does not rush the cloud. Why should you?",
  "Meditation is not escape. It is returning the keys.",
  "Listen until listening becomes rest.",
  "Soft shoulders teach the mind manners.",
  "Enough is a place. Visit it often.",
  "The tea cools whether you worry or not.",
  "Let tonight be a shore, not a courtroom.",
  "Your worth is not a moving target.",
  "Sit with the ordinary. It is already sacred.",
  "A kind pause is a form of prayer.",
  "Do not decorate the silence. Inhabit it.",
  "The breath does not ask who you were yesterday.",
  "Walk as if the ground is a friend.",
  "Let one thought pass without a handshake.",
  "Quiet is not the absence of life. It is the room for it.",
  "You may put the armor down in this hour.",
  "The heart knows how to sit. Follow it.",
  "Rest is not a reward you earn from exhaustion.",
  "Let the hands be empty of proving.",
  "Peace begins where the argument with now ends.",
  "A slow exhale is a door.",
  "Be the weather, not the forecast.",
  "The body is not a project this morning.",
  "What is here is enough to begin.",
  "Let the eyes rest on one honest thing.",
  "Still water is still doing its work.",
  "You can be gentle and still be true.",
  "The night does not require a conclusion.",
  "Sit until the hurry becomes a rumor.",
  "Forgive the mind for being a mind.",
  "A candle does not compete with the dark. It simply is.",
  "Leave a little space around every yes.",
  "The quiet you seek is already breathing you.",
  "Let hunger for more take a seat outside.",
  "Presence is the only luggage you need.",
  "Even the restless heart can learn to sit.",
  "Do not wait for perfect calm. Sit inside the weather.",
  "A kind word to yourself counts as practice.",
  "The window is a teacher if you let it be.",
  "Let the spine be a quiet tree.",
  "You are not late for your own life.",
  "Breathe into the places that braced.",
  "Peace is a practice of returning, not arriving.",
  "Let the day be smaller than your breath.",
  "The unsaid can rest too.",
  "Sit with what is, not with what should have been.",
  "Your attention is a garden. Weed it kindly.",
  "The ocean does not apologize for its tides.",
  "Let one minute be a monastery.",
  "Soft eyes. Soft clock.",
  "What you water with worry grows. Water stillness instead.",
  "The body remembers peace longer than the story does.",
  "You may begin again in the middle of the sentence.",
  "Let the shoulders drop the invisible luggage.",
  "Silence is not a test you can fail.",
  "A warm cup is a complete philosophy.",
  "The path is the sitting. Not the after.",
  "Be on the side of your own nervous system.",
  "Let dusk arrive without a verdict.",
  "The mind collects. The breath releases.",
  "You do not owe the world a performance of calm.",
  "Stay until the inside catches up with the chair.",
  "Peace prefers small rooms and honest hours.",
  "Let the feet feel the floor as a vow.",
  "Nothing extra is required for this inhale.",
  "The guru in the head is often just a tired voice. Let it sit.",
  "Kindness is a posture. Begin at the neck.",
  "Let tomorrow stay uninvited for one more breath.",
  "A slow morning is not wasted.",
  "The heart can be a still pond and still be deep.",
  "You are allowed to need quiet without explaining why.",
  "Let the ribs widen like a small yes.",
  "Practice is returning when you notice you left.",
  "The world will keep spinning. You may sit.",
  "Do not argue with the breath. Join it.",
  "A gentle gaze is already meditation.",
  "Let the name of the worry float without a hook.",
  "Peace is closer than the next notification.",
  "The body is speaking. Lower the volume of the plan.",
  "Sit as if friendship with yourself is the point.",
  "Let the exhale take what the day piled on.",
  "You can love people and still need a closed door.",
  "The quiet ones are not empty. They are listening.",
  "Let rain be a metronome for the heart.",
  "A bowed head can be strength, not defeat.",
  "Stop auditioning for your own approval.",
  "The present does not need a caption.",
  "Let warmth in the belly be the altar.",
  "Meditation is hospitality toward this moment.",
  "You may be a beginner every time you sit. Good.",
  "Let the tongue rest from defending.",
  "The oldest wisdom is often the slowest breath.",
  "Be where the feet are.",
  "A held breath is a held life. Let it go.",
  "The room is enough. You are enough. Begin.",
  "Let evening undo the knot without a story.",
  "Peace is not a personality. It is a permission.",
  "Sit with the child inside until they unclench.",
  "The mountain is not impressed by your speed.",
  "Let one kind thought complete its sentence.",
  "You cannot miss a breath that is happening now.",
  "The work of peace is mostly not leaving.",
  "Let the forehead smooth like tide over sand.",
  "A quiet yes is louder than a crowded plan.",
  "Stillness will not mock your restlessness.",
  "Let the hands uncurl. The world can wait that long.",
  "What is simple is not small.",
  "Breathe as if you belong here. You do.",
  "The teacher is the next honest pause.",
  "Let the heart have an afternoon off from proving.",
  "Peace likes repetition. Return.",
  "You may put down the future for the length of a cup.",
  "Let the eyes close on mercy, not on escape.",
  "The body is the first monastery.",
  "Sit until gratitude finds a seat without being invited.",
  "A slow walk is a moving silence.",
  "Let the question rest before it becomes a trial.",
  "You are not required to be interesting while you rest.",
  "The night sky does not hustle the stars.",
  "Let kindness arrive before the critique.",
  "Peace is the art of not adding a second arrow.",
  "Sit with the breath until it sits with you.",
  "The door to now is never locked.",
  "Let your name be spoken only by this inhale.",
  "A soft belly is a revolutionary act.",
  "The mind writes novels. The breath writes one word: here.",
  "Let waiting become watching, then become rest.",
  "You can put the verdict down and keep the life.",
  "Stillness is loyal. It stays when you return.",
  "Let the shoulders hear they are not load-bearing walls.",
  "Peace does not require a scenic view. A chair will do.",
  "The simplest altar is two feet on the ground.",
  "Let the day end without a scoreboard.",
  "You are allowed to be held by ordinary light.",
  "Sit like the tree: no speech, plenty of life.",
  "Let the next breath be unambitious.",
  "The heart learns peace the way rivers learn stones: slowly.",
  "Do not outsource your calm to a future version of you.",
  "Let the room be dim and the attention warm.",
  "A quiet meal is a meditation with a spoon.",
  "The pause is not lazy. It is precise.",
  "Let go of the pose. Keep the sitting.",
  "You may love the world better after you rest inside it.",
  "Peace is contagious. Start the outbreak in your chest.",
  "Let the ankles, the wrists, the jaw — all of them — resign.",
  "The guru page is this breath. Read it slowly.",
  "Sit with the ones you miss without leaving the chair.",
  "Let dawn be a teacher who does not raise her voice.",
  "A clear table can clear a mind.",
  "The work is to notice, not to win noticing.",
  "Let your inner weather pass without a press conference.",
  "You do not have to become someone else to be still.",
  "Peace keeps no attendance sheet.",
  "Let the spine rise and the story sit.",
  "The kindest schedule includes empty minutes on purpose.",
  "Sit until the inside and the chair agree.",
  "Let water on the face be a small baptism of now.",
  "The future is a guest. Do not give it the keys tonight.",
  "Breathe through the soles. The earth is listening.",
  "Let the eyebrow unknit the argument.",
  "You are already in the temple. It is called a body.",
  "Peace is what remains when you stop decorating fear.",
  "Let one song play without a second screen.",
  "The quiet after laughter is also holy.",
  "Sit as if your ancestors would like a turn to rest too.",
  "Let the phone sleep. Let you wake.",
  "A slower swallow. A slower life.",
  "The mind will come back. Greet it like a dog, then sit.",
  "Let mercy be the first interpretation.",
  "You may be tired. Sit anyway. Especially then.",
  "Peace is not a mood. It is a way of placing the feet.",
  "Let the ribs count a kinder rhythm.",
  "The world is loud. Your inner room has a door.",
  "Sit with joy as carefully as you sit with ache.",
  "Let the unsolved remain unsolved until morning.",
  "A bowed breath is still a complete breath.",
  "The teacher you wanted may be the pause you keep skipping.",
  "Let heat leave the face. Let cool stay in the chest.",
  "You can stop climbing for the length of a sit.",
  "Peace likes people who return without drama.",
  "Let the fingers forget the keyboard for a minute.",
  "The horizon is a slow idea. Copy it.",
  "Sit until the inner narrator loses interest.",
  "Let this hour be untitled.",
  "A kind spine is a kind mind waiting to happen.",
  "The breath you ignored is still willing.",
  "Let the house be imperfect and the sitting be true.",
  "You are not behind. You are here.",
  "Peace is a small lamp. Shield it with your hours.",
  "Let the tongue rest on the floor of the mouth like a leaf.",
  "The only race is back to the body.",
  "Sit with the truth that you are already held.",
  "Let birds finish their sentence before you start yours.",
  "A quiet person can still move the room toward rest.",
  "The practice is to stop leaving yourself.",
  "Let the inhale be welcome and the exhale be trust.",
  "You may put down being impressive. Pick up being present.",
  "Peace does not bill by the hour.",
  "Let the knees remember they can bend without collapsing.",
  "The night is a blanket if you stop picking at it.",
  "Sit as if the chair is a friend who waited.",
  "Let your inner child find the adult breathing slowly.",
  "A single candle is a crowd of light.",
  "The guru is the gap. Visit often.",
  "Let steam from the cup be a cloud you do not chase.",
  "You can be ambitious tomorrow. Tonight, be breath.",
  "Peace is the decision to stop tightening.",
  "Let the skull be a sky, not a factory.",
  "Sit until the word enough feels like a name.",
  "The body will tell you when the sit is honest.",
  "Let no one, including you, rush this swallow.",
  "A slow blink is a tiny night. Take it.",
  "The path of peace is mostly repetition with kindness.",
  "Let the heart stay unarmored for one song.",
  "You are allowed to outgrow noise.",
  "Sit with water. Learn its patience.",
  "Let the day be a river, not a courtroom transcript.",
  "Peace arrives on time. We are the ones who are early with worry.",
  "The simplest wisdom: come back.",
  "Let your name mean rest as much as it means doing.",
  "A still mouth can be a kind mouth.",
  "The practice does not require incense. It requires returning.",
  "Let the shoulders melt toward the earth that wants them.",
  "You may be ordinary. Ordinary is a beautiful altar.",
  "Sit until the next kind action becomes obvious.",
  "Let the mind's theater run. You are the seat, not the play.",
  "Peace is homemade. Start with the breath you have.",
  "The closed eyes are not hiding. They are arriving.",
  "Let one honest yawn be the gong.",
  "You do not have to understand the quiet to deserve it.",
  "Sit like dusk: no announcement, complete change.",
  "Let the ribs be a cradle for the tired heart.",
  "A gentle routine is a temple you can carry.",
  "The wisdom is not elsewhere. It is under the next breath.",
  "Let your inner critic sit in the back row without a microphone.",
  "Peace prefers unclenched hands.",
  "You may end the day without a lesson. Rest is the lesson.",
  "Sit with the people you love by being here, not by spinning.",
  "Let the floor take more of you than the plan does.",
  "The quiet is not judging your technique.",
  "A long exhale is a love letter to the nervous system.",
  "Let Mtulivu mean: I can be still and still belong.",
  "The head is full. Let the bubbles leave.",
  "Sit until the inside becomes a wide field.",
  "Let tonight forgive today.",
  "You are the sky. Thoughts are weather. Wait.",
  "Let the breath be enough.",
  "Let the breath arrive without a speech.",
  "Let the breath teach you patience.",
  "Let the breath remain unnamed.",
  "Let the breath keep you company.",
  "Let the breath finish what hurry started.",
  "Let the breath sit with you.",
  "Let the breath ask nothing extra.",
  "Let the breath soften the jaw.",
  "Let the breath hold the day.",
  "Let the breath return you to now.",
  "Let the breath unclench the story.",
  "Let the breath be a small monastery.",
  "Let the breath outlast the worry.",
  "Let the breath welcome you home.",
  "Nothing is late in the breath.",
  "The breath is already a teacher.",
  "The breath does not need an audience.",
  "Peace often looks like the breath.",
  "Begin again at the breath.",
  "You can meet the breath without a plan.",
  "Trust the breath more than the forecast.",
  "If you are lost, return to the breath.",
  "Let this hour be enough.",
  "Let this hour arrive without a speech.",
  "Let this hour teach you patience.",
  "Let this hour remain unnamed.",
  "Let this hour keep you company.",
  "Let this hour finish what hurry started.",
  "Let this hour sit with you.",
  "Let this hour ask nothing extra.",
  "Let this hour soften the jaw.",
  "Let this hour hold the day.",
  "Let this hour return you to now.",
  "Let this hour unclench the story.",
  "Let this hour be a small monastery.",
  "Let this hour outlast the worry.",
  "Let this hour welcome you home.",
  "Nothing is late in this hour.",
  "This hour is already a teacher.",
  "This hour does not need an audience.",
  "Sit with this hour until it sits with you.",
  "Peace often looks like this hour.",
  "Begin again at this hour.",
  "You can meet this hour without a plan.",
  "Trust this hour more than the forecast.",
  "If you are lost, return to this hour.",
  "Let the body arrive without a speech.",
  "Let the body teach you patience.",
  "Let the body remain unnamed.",
  "Let the body keep you company.",
  "Let the body finish what hurry started.",
  "Let the body sit with you.",
  "Let the body ask nothing extra.",
  "Let the body soften the jaw.",
  "Let the body hold the day.",
  "Let the body return you to now.",
  "Let the body unclench the story.",
  "Let the body be a small monastery.",
  "Let the body outlast the worry.",
  "Let the body welcome you home.",
  "Nothing is late in the body.",
  "The body is already a teacher.",
  "The body does not need an audience.",
  "Sit with the body until it sits with you.",
  "Peace often looks like the body.",
  "Begin again at the body.",
  "You can meet the body without a plan.",
  "Trust the body more than the forecast.",
  "If you are lost, return to the body.",
  "Let the quiet be enough.",
  "Let the quiet arrive without a speech.",
  "Let the quiet teach you patience.",
  "Let the quiet remain unnamed.",
  "Let the quiet keep you company.",
  "Let the quiet finish what hurry started.",
  "Let the quiet sit with you.",
  "Let the quiet ask nothing extra.",
  "Let the quiet soften the jaw.",
  "Let the quiet hold the day.",
  "Let the quiet return you to now.",
  "Let the quiet unclench the story.",
  "Let the quiet be a small monastery.",
  "Let the quiet outlast the worry.",
  "Let the quiet welcome you home.",
  "Nothing is late in the quiet.",
  "The quiet is already a teacher.",
  "The quiet does not need an audience.",
  "Sit with the quiet until it sits with you.",
  "Peace often looks like the quiet.",
  "Begin again at the quiet.",
  "You can meet the quiet without a plan.",
  "Trust the quiet more than the forecast.",
  "If you are lost, return to the quiet.",
  "Let the pause be enough.",
  "Let the pause arrive without a speech.",
  "Let the pause teach you patience.",
  "Let the pause remain unnamed.",
  "Let the pause keep you company.",
  "Let the pause finish what hurry started.",
  "Let the pause sit with you.",
  "Let the pause ask nothing extra.",
  "Let the pause soften the jaw.",
  "Let the pause hold the day.",
  "Let the pause return you to now.",
  "Let the pause unclench the story.",
  "Let the pause be a small monastery.",
  "Let the pause outlast the worry.",
  "Let the pause welcome you home.",
  "Nothing is late in the pause.",
  "The pause is already a teacher.",
  "The pause does not need an audience.",
  "Sit with the pause until it sits with you.",
  "Peace often looks like the pause.",
  "Begin again at the pause.",
  "You can meet the pause without a plan.",
  "Trust the pause more than the forecast.",
  "If you are lost, return to the pause.",
  "Let your hands be enough.",
  "Let your hands arrive without a speech.",
  "Let your hands teach you patience.",
  "Let your hands remain unnamed.",
  "Let your hands keep you company.",
  "Let your hands finish what hurry started.",
  "Let your hands sit with you.",
  "Let your hands ask nothing extra.",
  "Let your hands soften the jaw.",
  "Let your hands hold the day.",
  "Let your hands return you to now.",
  "Let your hands unclench the story.",
  "Let your hands be a small monastery.",
  "Let your hands outlast the worry.",
  "Let your hands welcome you home.",
  "Nothing is late in your hands.",
  "Your hands is already a teacher.",
  "Your hands does not need an audience.",
  "Sit with your hands until it sits with you.",
  "Peace often looks like your hands.",
  "Begin again at your hands.",
  "You can meet your hands without a plan.",
  "Trust your hands more than the forecast.",
  "If you are lost, return to your hands.",
  "Let the morning be enough.",
  "Let the morning teach you patience.",
  "Let the morning remain unnamed.",
  "Let the morning keep you company.",
  "Let the morning finish what hurry started.",
  "Let the morning sit with you.",
  "Let the morning ask nothing extra.",
  "Let the morning soften the jaw.",
  "Let the morning hold the day.",
  "Let the morning return you to now.",
  "Let the morning unclench the story.",
  "Let the morning be a small monastery.",
  "Let the morning outlast the worry.",
  "Let the morning welcome you home.",
  "Nothing is late in the morning.",
  "The morning is already a teacher.",
  "The morning does not need an audience.",
  "Sit with the morning until it sits with you.",
  "Peace often looks like the morning.",
  "Begin again at the morning.",
  "You can meet the morning without a plan.",
  "Trust the morning more than the forecast.",
  "If you are lost, return to the morning.",
  "Let the night be enough.",
  "Let the night arrive without a speech.",
  "Let the night teach you patience.",
  "Let the night remain unnamed.",
  "Let the night keep you company.",
  "Let the night finish what hurry started.",
  "Let the night sit with you.",
  "Let the night ask nothing extra.",
  "Let the night soften the jaw.",
  "Let the night hold the day.",
  "Let the night return you to now.",
  "Let the night unclench the story.",
  "Let the night be a small monastery.",
  "Let the night outlast the worry.",
  "Let the night welcome you home.",
  "Nothing is late in the night.",
  "The night is already a teacher.",
  "The night does not need an audience.",
  "Sit with the night until it sits with you.",
  "Peace often looks like the night.",
  "Begin again at the night.",
  "You can meet the night without a plan.",
  "Trust the night more than the forecast.",
  "If you are lost, return to the night.",
  "Let the window be enough.",
  "Let the window arrive without a speech.",
  "Let the window teach you patience.",
  "Let the window remain unnamed.",
  "Let the window keep you company.",
  "Let the window finish what hurry started.",
  "Let the window sit with you.",
  "Let the window ask nothing extra.",
  "Let the window soften the jaw.",
  "Let the window hold the day.",
  "Let the window return you to now.",
  "Let the window unclench the story.",
  "Let the window be a small monastery.",
  "Let the window outlast the worry.",
  "Let the window welcome you home.",
  "Nothing is late in the window.",
  "The window is already a teacher.",
  "The window does not need an audience.",
  "Sit with the window until it sits with you.",
  "Peace often looks like the window.",
  "Begin again at the window.",
  "You can meet the window without a plan.",
  "Trust the window more than the forecast.",
  "If you are lost, return to the window.",
  "Let the tea arrive without a speech.",
  "Let the tea teach you patience.",
  "Let the tea remain unnamed.",
  "Let the tea keep you company.",
  "Let the tea finish what hurry started.",
  "Let the tea sit with you.",
  "Let the tea ask nothing extra.",
  "Let the tea soften the jaw.",
  "Let the tea hold the day.",
  "Let the tea return you to now.",
  "Let the tea unclench the story.",
  "Let the tea be a small monastery.",
  "Let the tea outlast the worry.",
  "Let the tea welcome you home.",
  "Nothing is late in the tea.",
  "The tea is already a teacher.",
  "The tea does not need an audience.",
  "Sit with the tea until it sits with you.",
  "Peace often looks like the tea.",
  "You can meet the tea without a plan.",
  "Trust the tea more than the forecast.",
  "If you are lost, return to the tea.",
  "Let the walking be enough.",
  "Let the walking arrive without a speech.",
  "Let the walking teach you patience.",
  "Let the walking remain unnamed.",
  "Let the walking keep you company.",
  "Let the walking finish what hurry started.",
  "Let the walking sit with you.",
  "Let the walking ask nothing extra.",
  "Let the walking soften the jaw.",
  "Let the walking hold the day.",
  "Let the walking return you to now.",
  "Let the walking unclench the story.",
  "Let the walking be a small monastery.",
  "Let the walking outlast the worry.",
  "Let the walking welcome you home.",
  "Nothing is late in the walking.",
  "The walking is already a teacher.",
  "The walking does not need an audience.",
  "Sit with the walking until it sits with you.",
  "Peace often looks like the walking.",
  "Begin again at the walking.",
  "You can meet the walking without a plan.",
  "Trust the walking more than the forecast.",
  "If you are lost, return to the walking.",
  "Let the chest be enough.",
  "Let the chest arrive without a speech.",
  "Let the chest teach you patience.",
  "Let the chest remain unnamed.",
  "Let the chest keep you company.",
  "Let the chest finish what hurry started.",
  "Let the chest sit with you.",
  "Let the chest ask nothing extra.",
  "Let the chest soften the jaw.",
  "Let the chest hold the day.",
  "Let the chest return you to now.",
  "Let the chest unclench the story.",
  "Let the chest be a small monastery.",
  "Let the chest outlast the worry.",
  "Let the chest welcome you home.",
  "Nothing is late in the chest.",
  "The chest is already a teacher.",
  "The chest does not need an audience.",
  "Sit with the chest until it sits with you.",
  "Peace often looks like the chest.",
  "Begin again at the chest.",
  "You can meet the chest without a plan.",
  "Trust the chest more than the forecast.",
  "If you are lost, return to the chest.",
  "Let the ground be enough.",
  "Let the ground arrive without a speech.",
  "Let the ground teach you patience.",
  "Let the ground remain unnamed.",
  "Let the ground keep you company.",
  "Let the ground finish what hurry started.",
  "Let the ground sit with you.",
  "Let the ground ask nothing extra.",
  "Let the ground soften the jaw.",
  "Let the ground hold the day.",
  "Let the ground return you to now.",
  "Let the ground unclench the story.",
  "Let the ground be a small monastery.",
  "Let the ground outlast the worry.",
  "Let the ground welcome you home.",
  "Nothing is late in the ground.",
  "The ground is already a teacher.",
  "The ground does not need an audience.",
  "Sit with the ground until it sits with you.",
  "Peace often looks like the ground.",
  "Begin again at the ground.",
  "You can meet the ground without a plan.",
  "Trust the ground more than the forecast.",
  "If you are lost, return to the ground.",
  "Let this chair be enough.",
  "Let this chair arrive without a speech.",
  "Let this chair teach you patience.",
  "Let this chair remain unnamed.",
  "Let this chair keep you company.",
  "Let this chair finish what hurry started.",
  "Let this chair sit with you.",
  "Let this chair ask nothing extra.",
  "Let this chair soften the jaw.",
  "Let this chair hold the day.",
  "Let this chair return you to now.",
  "Let this chair unclench the story.",
  "Let this chair be a small monastery.",
  "Let this chair outlast the worry.",
  "Let this chair welcome you home.",
  "Nothing is late in this chair.",
  "This chair is already a teacher.",
  "This chair does not need an audience.",
  "Sit with this chair until it sits with you.",
  "Peace often looks like this chair.",
  "Begin again at this chair.",
  "You can meet this chair without a plan.",
  "Trust this chair more than the forecast.",
  "If you are lost, return to this chair.",
  "Let the dusk arrive without a speech.",
  "Let the dusk teach you patience.",
  "Let the dusk remain unnamed.",
  "Let the dusk keep you company.",
  "Let the dusk finish what hurry started.",
  "Let the dusk sit with you.",
  "Let the dusk ask nothing extra.",
  "Let the dusk soften the jaw.",
  "Let the dusk hold the day.",
  "Let the dusk return you to now.",
  "Let the dusk unclench the story.",
  "Let the dusk be a small monastery.",
  "Let the dusk outlast the worry.",
  "Let the dusk welcome you home.",
  "Nothing is late in the dusk.",
  "The dusk is already a teacher.",
  "The dusk does not need an audience.",
  "Sit with the dusk until it sits with you.",
  "Peace often looks like the dusk.",
  "Begin again at the dusk.",
  "You can meet the dusk without a plan.",
  "Trust the dusk more than the forecast.",
  "If you are lost, return to the dusk.",
  "Let the dawn arrive without a speech.",
  "Let the dawn teach you patience.",
  "Let the dawn remain unnamed.",
  "Let the dawn keep you company.",
  "Let the dawn finish what hurry started.",
  "Let the dawn sit with you.",
  "Let the dawn ask nothing extra.",
  "Let the dawn soften the jaw.",
  "Let the dawn hold the day.",
  "Let the dawn return you to now.",
  "Let the dawn unclench the story.",
  "Let the dawn be a small monastery.",
  "Let the dawn outlast the worry.",
  "Let the dawn welcome you home.",
  "Nothing is late in the dawn.",
  "The dawn is already a teacher.",
  "The dawn does not need an audience.",
  "Sit with the dawn until it sits with you.",
  "Peace often looks like the dawn.",
  "Begin again at the dawn.",
  "You can meet the dawn without a plan.",
  "Trust the dawn more than the forecast.",
  "If you are lost, return to the dawn.",
  "Let the rain arrive without a speech.",
  "Let the rain teach you patience.",
  "Let the rain remain unnamed.",
  "Let the rain keep you company.",
  "Let the rain finish what hurry started.",
  "Let the rain sit with you.",
  "Let the rain ask nothing extra.",
  "Let the rain soften the jaw.",
  "Let the rain hold the day.",
  "Let the rain return you to now.",
  "Let the rain unclench the story.",
  "Let the rain be a small monastery.",
  "Let the rain outlast the worry.",
  "Let the rain welcome you home.",
  "Nothing is late in the rain.",
  "The rain is already a teacher.",
  "The rain does not need an audience.",
  "Sit with the rain until it sits with you.",
  "Peace often looks like the rain.",
  "Begin again at the rain.",
  "You can meet the rain without a plan.",
  "Trust the rain more than the forecast.",
  "If you are lost, return to the rain.",
  "Let the river be enough.",
  "Let the river arrive without a speech.",
  "Let the river teach you patience.",
  "Let the river remain unnamed.",
  "Let the river keep you company.",
  "Let the river finish what hurry started.",
  "Let the river sit with you.",
  "Let the river ask nothing extra.",
  "Let the river soften the jaw.",
  "Let the river hold the day.",
  "Let the river return you to now.",
  "Let the river unclench the story.",
  "Let the river be a small monastery.",
  "Let the river outlast the worry.",
  "Let the river welcome you home.",
  "Nothing is late in the river.",
  "The river is already a teacher.",
  "The river does not need an audience.",
  "Sit with the river until it sits with you.",
  "Peace often looks like the river.",
  "Begin again at the river.",
  "You can meet the river without a plan.",
  "Trust the river more than the forecast.",
  "If you are lost, return to the river.",
  "Let the mountain be enough.",
  "Let the mountain arrive without a speech.",
  "Let the mountain teach you patience.",
  "Let the mountain remain unnamed.",
  "Let the mountain keep you company.",
  "Let the mountain finish what hurry started.",
  "Let the mountain sit with you.",
  "Let the mountain ask nothing extra.",
  "Let the mountain soften the jaw.",
  "Let the mountain hold the day.",
  "Let the mountain return you to now.",
  "Let the mountain unclench the story.",
  "Let the mountain be a small monastery.",
  "Let the mountain outlast the worry.",
  "Let the mountain welcome you home.",
  "Nothing is late in the mountain.",
  "The mountain is already a teacher.",
  "The mountain does not need an audience.",
  "Sit with the mountain until it sits with you.",
  "Peace often looks like the mountain.",
  "Begin again at the mountain.",
  "You can meet the mountain without a plan.",
  "Trust the mountain more than the forecast.",
  "If you are lost, return to the mountain.",
  "Let the candle be enough.",
  "Let the candle arrive without a speech.",
  "Let the candle teach you patience.",
  "Let the candle remain unnamed.",
  "Let the candle keep you company.",
  "Let the candle finish what hurry started.",
  "Let the candle sit with you.",
  "Let the candle ask nothing extra.",
  "Let the candle soften the jaw.",
  "Let the candle hold the day.",
  "Let the candle return you to now.",
  "Let the candle unclench the story.",
  "Let the candle be a small monastery.",
  "Let the candle outlast the worry.",
  "Let the candle welcome you home.",
  "Nothing is late in the candle.",
  "The candle is already a teacher.",
  "The candle does not need an audience.",
  "Sit with the candle until it sits with you.",
  "Peace often looks like the candle.",
  "Begin again at the candle.",
  "You can meet the candle without a plan.",
  "Trust the candle more than the forecast.",
  "If you are lost, return to the candle.",
  "Let the garden be enough.",
  "Let the garden arrive without a speech.",
  "Let the garden teach you patience.",
  "Let the garden remain unnamed.",
  "Let the garden keep you company.",
  "Let the garden finish what hurry started.",
  "Let the garden sit with you.",
  "Let the garden ask nothing extra.",
  "Let the garden soften the jaw.",
  "Let the garden hold the day.",
  "Let the garden return you to now.",
  "Let the garden unclench the story.",
  "Let the garden be a small monastery.",
  "Let the garden outlast the worry.",
  "Let the garden welcome you home.",
  "Nothing is late in the garden.",
  "The garden is already a teacher.",
  "The garden does not need an audience.",
  "Sit with the garden until it sits with you.",
  "Peace often looks like the garden.",
  "Begin again at the garden.",
  "You can meet the garden without a plan.",
  "Trust the garden more than the forecast.",
  "If you are lost, return to the garden.",
  "Let the shore be enough.",
  "Let the shore arrive without a speech.",
  "Let the shore teach you patience.",
  "Let the shore remain unnamed.",
  "Let the shore keep you company.",
  "Let the shore finish what hurry started.",
  "Let the shore sit with you.",
  "Let the shore ask nothing extra.",
  "Let the shore soften the jaw.",
  "Let the shore hold the day.",
  "Let the shore return you to now.",
  "Let the shore unclench the story.",
  "Let the shore be a small monastery.",
  "Let the shore outlast the worry.",
  "Let the shore welcome you home.",
  "Nothing is late in the shore.",
  "The shore is already a teacher.",
  "The shore does not need an audience.",
  "Sit with the shore until it sits with you.",
  "Peace often looks like the shore.",
  "Begin again at the shore.",
  "You can meet the shore without a plan.",
  "Trust the shore more than the forecast.",
  "If you are lost, return to the shore.",
  "Let the sky arrive without a speech.",
  "Let the sky teach you patience.",
  "Let the sky remain unnamed.",
  "Let the sky keep you company.",
  "Let the sky finish what hurry started.",
  "Let the sky sit with you.",
  "Let the sky ask nothing extra.",
  "Let the sky soften the jaw.",
  "Let the sky hold the day.",
  "Let the sky return you to now.",
  "Let the sky unclench the story.",
  "Let the sky be a small monastery.",
  "Let the sky outlast the worry.",
  "Let the sky welcome you home.",
  "Nothing is late in the sky.",
  "The sky is already a teacher.",
  "The sky does not need an audience.",
  "Sit with the sky until it sits with you.",
  "Peace often looks like the sky.",
  "You can meet the sky without a plan.",
  "Trust the sky more than the forecast.",
  "If you are lost, return to the sky.",
  "Let the heart be enough.",
  "Let the heart arrive without a speech.",
  "Let the heart teach you patience.",
  "Let the heart remain unnamed.",
  "Let the heart keep you company.",
  "Let the heart finish what hurry started.",
  "Let the heart sit with you.",
  "Let the heart ask nothing extra.",
  "Let the heart soften the jaw.",
  "Let the heart hold the day.",
  "Let the heart return you to now.",
  "Let the heart unclench the story.",
  "Let the heart be a small monastery.",
  "Let the heart outlast the worry.",
  "Let the heart welcome you home.",
  "Nothing is late in the heart.",
  "The heart is already a teacher.",
  "The heart does not need an audience.",
  "Sit with the heart until it sits with you.",
  "Peace often looks like the heart.",
  "Begin again at the heart.",
  "You can meet the heart without a plan.",
  "Trust the heart more than the forecast.",
  "If you are lost, return to the heart.",
  "Let the spine be enough.",
  "Let the spine arrive without a speech.",
  "Let the spine teach you patience.",
  "Let the spine remain unnamed.",
  "Let the spine keep you company.",
  "Let the spine finish what hurry started.",
  "Let the spine sit with you.",
  "Let the spine ask nothing extra.",
  "Let the spine soften the jaw.",
  "Let the spine hold the day.",
  "Let the spine return you to now.",
  "Let the spine unclench the story.",
  "Let the spine be a small monastery.",
  "Let the spine outlast the worry.",
  "Let the spine welcome you home.",
  "Nothing is late in the spine.",
  "The spine is already a teacher.",
  "The spine does not need an audience.",
  "Sit with the spine until it sits with you.",
  "Peace often looks like the spine.",
  "Begin again at the spine.",
  "You can meet the spine without a plan.",
  "Trust the spine more than the forecast.",
  "If you are lost, return to the spine.",
  "Let the room arrive without a speech.",
  "Let the room teach you patience.",
  "Let the room remain unnamed.",
  "Let the room keep you company.",
  "Let the room finish what hurry started.",
  "Let the room sit with you.",
  "Let the room ask nothing extra.",
  "Let the room soften the jaw.",
  "Let the room hold the day.",
  "Let the room return you to now.",
  "Let the room unclench the story.",
  "Let the room be a small monastery.",
  "Let the room outlast the worry.",
  "Let the room welcome you home.",
  "Nothing is late in the room.",
  "The room is already a teacher.",
  "The room does not need an audience.",
  "Sit with the room until it sits with you.",
  "Peace often looks like the room.",
  "Begin again at the room.",
  "You can meet the room without a plan.",
  "Trust the room more than the forecast.",
  "If you are lost, return to the room.",
  "Let the cup arrive without a speech.",
  "Let the cup teach you patience.",
  "Let the cup remain unnamed.",
  "Let the cup keep you company.",
  "Let the cup finish what hurry started.",
  "Let the cup sit with you.",
  "Let the cup ask nothing extra.",
  "Let the cup soften the jaw.",
  "Let the cup hold the day.",
  "Let the cup return you to now.",
  "Let the cup unclench the story.",
  "Let the cup be a small monastery.",
  "Let the cup outlast the worry.",
  "Let the cup welcome you home.",
  "Nothing is late in the cup.",
  "The cup is already a teacher.",
  "The cup does not need an audience.",
  "Sit with the cup until it sits with you.",
  "Peace often looks like the cup.",
  "You can meet the cup without a plan.",
  "Trust the cup more than the forecast.",
  "If you are lost, return to the cup.",
  "Let the path arrive without a speech.",
  "Let the path teach you patience.",
  "Let the path remain unnamed.",
  "Let the path keep you company.",
  "Let the path finish what hurry started.",
  "Let the path sit with you.",
  "Let the path ask nothing extra.",
  "Let the path soften the jaw.",
  "Let the path hold the day.",
  "Let the path return you to now.",
  "Let the path unclench the story.",
  "Let the path be a small monastery.",
  "Let the path outlast the worry.",
  "Let the path welcome you home.",
  "Nothing is late in the path.",
  "The path is already a teacher.",
  "The path does not need an audience.",
  "Sit with the path until it sits with you.",
  "Peace often looks like the path.",
  "Begin again at the path.",
  "You can meet the path without a plan.",
  "Trust the path more than the forecast.",
  "If you are lost, return to the path.",
  "Let the silence be enough.",
  "Let the silence arrive without a speech.",
  "Let the silence teach you patience.",
  "Let the silence remain unnamed.",
  "Let the silence keep you company.",
  "Let the silence finish what hurry started.",
  "Let the silence sit with you.",
  "Let the silence ask nothing extra.",
  "Let the silence soften the jaw.",
  "Let the silence hold the day.",
  "Let the silence return you to now.",
  "Let the silence unclench the story.",
  "Let the silence be a small monastery.",
  "Let the silence outlast the worry.",
  "Let the silence welcome you home.",
  "Nothing is late in the silence.",
  "The silence is already a teacher.",
  "The silence does not need an audience.",
  "Sit with the silence until it sits with you.",
  "Peace often looks like the silence.",
  "Begin again at the silence.",
  "You can meet the silence without a plan.",
  "Trust the silence more than the forecast.",
  "If you are lost, return to the silence.",
  "Let the light be enough.",
  "Let the light arrive without a speech.",
  "Let the light teach you patience.",
  "Let the light remain unnamed.",
  "Let the light keep you company.",
  "Let the light finish what hurry started.",
  "Let the light sit with you.",
  "Let the light ask nothing extra.",
  "Let the light soften the jaw.",
  "Let the light hold the day.",
  "Let the light return you to now.",
  "Let the light unclench the story.",
  "Let the light be a small monastery.",
  "Let the light outlast the worry.",
  "Let the light welcome you home.",
  "Nothing is late in the light.",
  "The light is already a teacher.",
  "The light does not need an audience.",
  "Sit with the light until it sits with you.",
  "Peace often looks like the light.",
  "Begin again at the light.",
  "You can meet the light without a plan.",
  "Trust the light more than the forecast.",
  "If you are lost, return to the light.",
  "You do not have to earn stillness to sit.",
  "You do not have to earn stillness to rest.",
  "You do not have to earn stillness to begin again.",
  "You do not have to earn stillness to be here.",
  "You do not have to earn stillness to listen.",
  "You do not have to earn stillness to breathe.",
  "You do not have to earn stillness to soften.",
  "You do not have to earn stillness to stay.",
  "You do not have to earn stillness to belong.",
  "You do not have to earn stillness to let go.",
  "You do not have to earn stillness to come back.",
  "You do not have to earn stillness to be unfinished.",
  "You do not have to earn stillness to close the eyes.",
  "You do not have to earn stillness to put the armor down.",
  "You do not have to earn stillness to drink the tea slowly.",
  "You do not have to explain your tiredness to sit.",
  "You do not have to explain your tiredness to rest.",
  "You do not have to explain your tiredness to begin again.",
  "You do not have to explain your tiredness to be here.",
  "You do not have to explain your tiredness to listen.",
  "You do not have to explain your tiredness to breathe.",
  "You do not have to explain your tiredness to soften.",
  "You do not have to explain your tiredness to stay.",
  "You do not have to explain your tiredness to belong.",
  "You do not have to explain your tiredness to let go.",
  "You do not have to explain your tiredness to come back.",
  "You do not have to explain your tiredness to be unfinished."
];
